#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=/home/komil/.fnm:$PATH

eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# fnm
# export PATH=/home/komil/.fnm:$PATH
# eval "$(fnm env)"

# autin
export ATUIN_NOBIND="true"
eval "$(atuin init zsh)"

bindkey '^r' _atuin_search_widget

# depends on terminal mode
bindkey '^[[A' _atuin_search_widget
bindkey '^[OA' _atuin_search_widget
bindkey '^[[Z' reverse-menu-complete

# starship
eval "$(starship init zsh)"

# fuck
eval $(thefuck --alias)

# nvm
# export NVM_DIR="$HOME/.config/nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# deno
export DENO_INSTALL="/home/komil/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
